<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.LocalIntros</RootNamespace>
    <AssemblyVersion>2.2.0.100</AssemblyVersion>
    <FileVersion>2.2.0.100</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.*-*" />
    <PackageReference Include="Jellyfin.Model" Version="12.*-*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\config.html" />
    <EmbeddedResource Include="Configuration\config.html" />
  </ItemGroup>

</Project>
